#define _CRT_SECURE_NO_WARNINGS

#include "logger.h"
#include <windows.h>

static FILE* log_file = NULL;

void get_next_log_filename(char* filename) {
	int highest_run_number = 0;

	WIN32_FIND_DATA findFileData; // this structure is used to describe the file found by FindFirstFile or FindNextFile https://learn.microsoft.com/en-us/previous-versions/ms915521(v=msdn.10) (add ')' to url, it seems to not stay when you click it)
	HANDLE hFind = FindFirstFile("logs_run_*.txt", &findFileData); // look for any log file that matches our auto-generated syntax

	if (hFind == INVALID_HANDLE_VALUE) {
		// no proper log files exist in the directory from previous runs
		// create first run log
		sprintf(filename, "logs_run_1.txt");
		return;
	}

	do {
		int run_number;
		// use sscanf to scan the run number from the name of the file found (useful docs on scanning functions: https://www.ibm.com/docs/en/ztpf/2023?topic=apis-fscanf-scanf-sscanf-read-format-data)
		if (sscanf(findFileData.cFileName, "logs_run_%d.txt", &run_number) == 1) {
			// if this run number is bigger than any we have encountered
			if (run_number > highest_run_number) {
				// set highest as current
				highest_run_number = run_number;
			}
		}
	} while (FindNextFile(hFind, &findFileData) != 0); // while there are more files matching our syntax in the directory

	FindClose(hFind); // close the file search handle https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findclose

	sprintf(filename, "logs_runs_%d.txt", highest_run_number + 1);
}

void init_log_file() {
	char filename[50]; // using 50 as max length, will not cross this with autogenerated syntax unless someone does zillions of runs (to be exact)

	// NOTE: there are errors with this function, it is not correctly finding files with the logs_run_X syntax, so it just uses logs_run_1 every time
	// this functionality will be included in our final solution so that users can maintain log history of previous runs
	//get_next_log_filename(filename);

	log_file = fopen("run_logs.txt", "w"); // just overwriting one file, instead of using the new logs run file, for now

	if (log_file == NULL) {
		fprintf(stderr, "Failed to open log file: %s\n", filename);
		exit(1);
	}

	// open the text file in the notepad (again using one file, not a new one for this run)
	ShellExecuteA(GetDesktopWindow(), "open", "run_logs.txt", NULL, NULL, SW_SHOW);

	// found someone trying to build the same experience in their program https://stackoverflow.com/questions/17417718/how-to-open-a-text-file-in-notepad-in-a-c-program
	// and here are the docs for ShellExecute (which is pretty cool) https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea?redirectedfrom=MSDN

	print_welcome_log();
}

void close_log_file() {
	if (log_file) {
		fclose(log_file);
		log_file = NULL;
	}
}

void log_message(const char* message) {
	if (log_file) {
		fprintf(log_file, "%s\n", message);
		fflush(log_file); // force the log to the output so we can see the live updates in the file
	}
}

void print_welcome_log() {
	log_message("Welcome to the Lunar Ice Cave Explorer (LICE) System!");
	log_message("---------------------------------------------------");
	log_message("This program allows you to create and explore a cave map.");
	log_message("Use the robot to draw and navigate through the cave, reading and setting cell attributes along the way.");
	log_message("");
	log_message("Valid Commands:");
	log_message("  - Arrow Keys: Move the robot (Up, Down, Left, Right)");
	log_message("  - 'c' Key: Set attributes for the current cell (elevation, friction, etc.)");
	log_message("  - Insert Key: Toggle between Movement and Drawing modes");
	log_message("  - Home Key: Exit the program");
	log_message("  - 'p' key: In Drawing mode, create portal, in Movement mode, use portal if on top of one");
	log_message("");
	log_message("Modes:");
	log_message("  - Movement Mode: Move the robot without leaving a trail.");
	log_message("  - Drawing Mode: Leave a tunnel trail as you move.");
	log_message("");
	log_message("Setting Cell Attributes:");
	log_message("  - In cell editing mode, press the lower case version of the attribute identifier to edit it");
	log_message("		- Ex: press 'r' to edit the R (radiation) attribute");
	log_message("  - After selecting which attribute to edit, enter the new value followed by the enter key");
	log_message("  - Press 'q' at any time to quit editing the cell");
	log_message("  - Home Key: Exit the program");
	log_message("  - 'p' key: ");
	log_message("");
	log_message("Logs:");
	log_message("  - In this window you will see logs for this run. Coordinates and cell attributes as you move, portal creation and usage, mode changes, etc.");
	log_message("  - Logs will only update when you are clicked on this editor. So, to refresh logs after making map changes, just click on this notepad.");
	log_message("");
	log_message("Enjoy exploring and mapping!");
	log_message("---------------------------------------------------");
	log_message("");
}

void print_unrecognized_command(char unrecognized_command) {
	char msg[100];

	sprintf(msg, "Unrecognized command: '%c'. Please refer to the available commands below.", unrecognized_command);
	log_message(msg);

	log_message("Valid Commands:");
	log_message("  - Arrow Keys: Move the robot (Up, Down, Left, Right)");
	log_message("  - 'c' Key: Set attributes for the current cell (elevation, friction, etc.)");
	log_message("  - Insert Key: Toggle between Movement and Drawing modes");
	log_message("  - Home Key: Exit the program");
	log_message("  - 'p' key: In Drawing mode, create portal, in Movement mode, use portal if on top of one");
	log_message("");
	log_message("Modes:");
	log_message("  - Movement Mode: Move the robot without leaving a trail.");
	log_message("  - Drawing Mode: Leave a tunnel trail as you move.");
	log_message("");
	log_message("Setting cell attributes:");
	log_message("  - In cell editing mode, press the lower case version of the attribute identifier to edit it");
	log_message("		- Ex: press 'r' to edit the R (radiation) attribute");
	log_message("  - After selecting which attribute to edit, enter the new value followed by the enter key");
	log_message("  - Press 'q' at any time to quit editing the cell");
	log_message("  - Home Key: Exit the program");
	log_message("  - 'p' key: ");
	log_message("");
	log_message("Please try again with a valid command.");
}